### ISSUE TITLE
Consolidate Pull Request for API POST Requests

### ISSUE THREAD

**Issue by patrickdugan** [OmniLayer/omniwallet#1220]
Going to need a bit of help from Tomas or Adam to nail down the specific JSON but here are the requests I will need to do dBanking and algo trading:

1) Dex trade - parameters: address, pair (or smart property id 1 and 2), order type, amount, price 

Needs to be broken down for the new tx types Zathras did, can someone link a reference?

2) Send to owners - parameters: address, payout currency, recipient currency

3) Create managed smart property - parameters: ibid the spec

4) Grant managed smart property - parameters: amount, address, STP ID

5) Revoke managed SP - ibid #4

Arguably the existing crowdsale transctions could be API supported but that's not a priority for me.

**Comment by achamely** [comment]
So the short update is that none of these calls/routes exist yet, 
Dex trades we have routes for v1 trades but nothing exists yet for v2 calls which will need to be developed based off the final setup of omnicore. 

2-5 are not too difficult (they are only minor tweaks on existing calls to create new ones) however I would really like to finish up / get the new UI rolled out so we can roll the new calls into it instead of having to try and backport calls into existing interface and then the new interface as well (double effort).  @Nevtep any chance we can get an update on where we stand ?

**Comment by patrickdugan** [comment]
https://github.com/bitpay/bitcoind-rpc

https://github.com/OmniLayer/omniwallet/blob/master/api/rpcclient.py

Ok we decided I should either modify the index file for Bitpay's .js wrapper to include Omni tx types, or utilize the existing Python client and wrap it into existing .js systems as needed.
