### ISSUE TITLE
why can not transfer

### ISSUE THREAD

**Issue by ForestCoin** [OmniLayer/omniwallet#1493]
1K9R6ZUuqEyMRcuEGE2B6kAgD683ToXD6u     I turn out many days before, can also be found, explore records are not now. Or not transfer success

**Comment by achamely** [comment]
@ForestCoin , 
What are you trying to transfer? 
Checking your address, 1K9R6ZUuqEyMRcuEGE2B6kAgD683ToXD6u ,  it currently has no assets/nothing on it at all.

**Comment by ForestCoin** [comment]
e528516428ef944e3a00c10dace081f407c61ddfe33c59cee4128ba458a32bb5      my synereo has been transfered.   but  there is  INVALID!  where is my synereo?

**Comment by ForestCoin** [comment]
@achamely     e528516428ef944e3a00c10dace081f407c61ddfe33c59cee4128ba458a32bb5   
                      this is  txid.   but my  synereo is losed?

**Comment by achamely** [comment]
that txid was invalid because the sending address did a double send and had already sent the AMP's in tx http://omniexplorer.info/lookuptx.aspx?txid=455d5a73373c8889e29c4fd73d63d77d295255730ec14deb3a60f18bd1822869

If you look at the sending history for that address you can see the 2 sends took place right after eachother: http://omniexplorer.info/lookupadd.aspx?address=1GMWNmPSAW54JirPi7vpNopeTZS6gkYaKh
and only the first one was valid because the sending address only had that much balance left to send.
