### ISSUE TITLE
Error message "Server Error" whenever attempting to send coin

### ISSUE THREAD

**Issue by 37355078** [OmniLayer/omniwallet#1494]
I am trying to send coin from my omni wallet to another onmi wallet. Im sure address is correct, because that same wallet address has sent coin to my wallet address successfully. I have sent coin from my wallet to other addresses, but that has been some time ago like 1 month ago.

**Comment by aghamir** [comment]
I have the same problem:
![image](https://user-images.githubusercontent.com/1880925/42306650-1cedbf90-8045-11e8-898a-33977b64ebfb.png)

I believe that occurs because of old armory(See https://github.com/goatpig/BitcoinArmory/issues/501).
It raises bad gateway when posting request to https://www.omniwallet.org/v1/armory/getunsigned. I think if omnilayer update armory(new repo) this will be solved.

**Comment by achamely** [comment]
This should have been already resolved in previous updates. if you continue to have issues please reach out to our support team
