### ISSUE TITLE
Accidentally deposited USDT in My BTC address in GDAX

### ISSUE THREAD

**Issue by 721121** [OmniLayer/omniwallet#1597]
and now my money appears in tetherUS(#31) I do not know how to recover my money, someone could please explain my steps to recover my money

**Comment by achamely** [comment]
Unfortunately you have sent your tokens to a wallet/service (Coinbase/Gdax) that does not support the Omni Protocol and there is little that can be done without the direct involvement of their support team. All Omni Protocol tokens, Like Tether, are owned/controlled by the address they currently exist on. In your case you sent them to an address owned/controlled by Coinbase/Gdax. In order to move those tokens the sending service/wallet needs to be able either be able to create an Omni Protocol Transaction, or sign a precreated Omni Protocol Transaction, or have the ability to export the private key for the address in question so you can import it into a wallet/service that supports the Omni Protocol. 

At this time you will need to reach out to their support team and request their assistance in a recovery process. We are more than willing to work with them/you to assist in the technical details but since the address in questions is associated with your account you will need to start the support dialog with them first. 

At the most basic level they will need to either be able to sign a premade transaction originating from your account address, or have a mechanism that allows you to send a transaction from the address your Tether are on that includes an OP_RETURN output. 

Once you get the appropriate support person involved you can loop our support team in and we can assist.

**Comment by achamely** [comment]
@gelinasgm unfortunately no
If you sent the funds to a coinbase address, Coinbase would have to be willing to work with you/us for any recovery options. If they are not then the funds are essentially stuck
