### ISSUE TITLE
"error": "Not enough funds, try again. Needed: 0.00008987999999999999495867240157 but Have: 0.00000546"

### ISSUE THREAD

**Issue by gillbates** [OmniLayer/omniwallet#1693]
Dear OmniWallet Team,

When I try to send usdt to my other wallet, the system will return ""error": "Not enough funds, try again. Needed: 0.00008987999999999999495867240157 but Have: 0.00000546" after send.
However I have more than this on address for both btc and usdt.  Any ideas why?

**Comment by achamely** [comment]
@gillbates sorry for the delayed response. 
The most common cause of that error is because the btc funds on your address might still be unconfirmed. 
Omniwallet can only create txs from confirmed funds so if your btc is still unconfirmed wait for it to confirm then try again. 
Also, When creating an omnilayer transaction you will need both BTC and the token you are sending and they are not interchangeable. 
i.e. you can not pay the transaction cost/miner fees with USDt, the sending address will have to have enough btc to create the transaction. 
(At this time bitcoin miners do not accept USDt for transaction costs, maybe that will change one day :) )

**Comment by Ozkman26** [comment]
How long does it take to confirm? I've been waiting 3 days now
