### ISSUE TITLE
How to Recovering funds from a Segwit Address?

### ISSUE THREAD

**Issue by gaoShuaiGitHub** [OmniLayer/omniwallet#1696]
hi:

i have read the article of "Recovering funds from a Segwit Address"
link：https://github.com/OmniLayer/omniwallet/issues/new
but my question is a bit different.
i sent the USDT to segwit address of the UBTC.
(USDT address like this:17tHuQJgUB77bgkNopT2baNN9CMvSQpjHX. 
UBTC address like this:3QQQE2qHjjzcEfUmDcUxx6LRFPKHxV4UtS)
do you know how i can get back my usdt?
I am very anxious, thank you very much for providing the method.

**Comment by gaoShuaiGitHub** [comment]
sorry  i have a mistake .the right link is:https://github.com/OmniLayer/omniwallet/issues/1696

**Comment by achamely** [comment]
@gaoShuaiGitHub if you read through the instructions on https://github.com/OmniLayer/omniwallet/wiki/Recovering-funds-from-a-Segwit-Address it does show on step 3 that in order for the recovery method to recognize a segwit address starting with 3 you need to import the private key with the p2wpkh-p2sh: prefix.  That should allow you to continue as expected.

**Comment by achamely** [comment]
@gaoShuaiGitHub it should be possible to still use this process to with an offline wallet with a little modification.

You'll need to install electrum on both your Offline and Online computers. 
On your Online computer instead of creating the wallet with the private key you'll add just your segwit address
On your offline computer you'll import the segwit private key according to the normal instructions. 

Then go through all the normal processes to create the recovery transaction on the online computer but instead of clicking the 'sign' button at the end you'll click the export button. 
This will give you an unsigned transaction file that you can take to your offline computer. 
You can then load it into your electrum client on the offline machine to sign. 
Once signed you can save the signed transaction to take back to your online computer and then you can broadcast it from there. 

In this way you do not need to bring the private key online but can still recover the files.

**Comment by gaoShuaiGitHub** [comment]
If I can't use electrum, I can only use the bitcoin-cli command on an offline computer. What should I do?

**Comment by achamely** [comment]
@gaoShuaiGitHub reach out to our support team email address https://www.omniwallet.org/about/contact and provide them with the address you sent the funds to (where the usdt currently are stuck) and where you want to recover/have the usdt moved to.  We can create the transaction manually for you and provide you with the signing instructions needed to use an offline bitcoin-core client to sign the transaction

**Comment by gaoShuaiGitHub** [comment]
Thank you very much, in the communication with you, I am also actively seeking ways, and finally the special application to use the btc electurm client to complete the signature and retrieve the usdt. thank you very much！
