### ISSUE TITLE
Http error 429

### ISSUE THREAD

**Issue by felipematheus** [OmniLayer/omniwallet#1698]
Description
We are using the omniexplorer api to manage usdt coins on our wallet, Lunes (https://luneswallet.app). Recently our requests to the omniexplorer api, on the endpoint https://api.omniwallet.org/v1/transaction/getunsigned/0 for example, have been receiving an error message as a response with the following content after making only one request to the omniwallet api. The user base of our wallet is still growing, so we would only make a few requests per day to the api.

errorMessage: "{"message":"Couldn't get list of unspent tx's. Response Code: 429","code":500,"type":"error","data":{}}"

Our requests are originating from amazon aws, and we believe we are receiving this error message because the amazon aws IP range are blacklisted in some way, because the same request on our local office IP with the same body content is not being throttled.

Is there anyway to whitelist the IP we are using to make the request or some payment form that would enable us to continue using the omniwallet api?

Thank you!

**Comment by achamely** [comment]
@felipematheus 
If you check the api documentation you'll notice this endpoint is not listed because it has not yet been refactored to be ready for public use.
Specifically, the error you are seeing is not actually from us as we were also having to use external apis during some of the transaction creation calls to get lists of unspent tx's and this is not scalable publicly.
Unfortunately even though the endpoint is unreleased there are still projects, like yourself, trying to use it which causes the timeouts from the other upstream api. 
Until its released we cannot guarantee any response from it or recommend it for any use.
