### ISSUE TITLE
trouble recovering funds

### ISSUE THREAD

**Issue by Doublef1000** [OmniLayer/omniwallet#1710]
Hello, december 2017 I sent 1776 tethers worth 1800 usd to a bitcoin wallet accidentally. Recently I tried to recover them using omniwallet however when I try to upload my btc wallet to recover the funds they say that the btc adress is not valid. Please could anyone assist me

**Comment by achamely** [comment]
@Doublef1000 
the bitcoin wallet you sent the funds to, which wallet/software is that?

**Comment by Doublef1000** [comment]
it was a copay adress
________________________________
De : Adam <notifications@github.com>
Envoyé : 25 mars 2019 11:32:06
À : OmniLayer/omniwallet
Cc : Doublef1000; Mention
Objet : Re: [OmniLayer/omniwallet] trouble recovering funds (#1710)


@Doublef1000<https://github.com/Doublef1000>
the bitcoin wallet you sent the funds to, which wallet/software is that?

**Comment by achamely** [comment]
@Doublef1000 copay/bitpay wallets have a format that is not directly compatible with omniwallet. However it is possible to convert the private key. Please take a look at our support article on recovering funds from a copay/bitpay wallet: https://github.com/OmniLayer/omniwallet/wiki/Finding-and-Exporting-your-private-key-from-Bitpay-Copay 
If you have issues let us know otherwise we'll close this issues in a few days
